### ISSUE TITLE
Unable to validate the web server

### ISSUE THREAD

**Issue by rajaseg** [elastic/connectors-ruby#238]
Hello Team,
I was able to build and run the custom connector using docker on the Ubuntu server. But unable to validate it.

Please find the below images for reference.

![image](https://user-images.githubusercontent.com/633479/183350104-1a609918-3804-4b35-8acf-26bd89910e65.png)

![image](https://user-images.githubusercontent.com/633479/183350257-a9b97d4c-3dd4-4351-98cf-3fd9aa6cca82.png)

![image](https://user-images.githubusercontent.com/633479/183350510-8848cef6-a542-4140-9d24-c5d0c069672e.png)

**Comment by tarekziade** [comment]
Hi Rajasekhar, 
The connectors service no longer uses a web server. It connects directly to the Elasticsearch server and polls.
I will fix the Dockerfile and link the changes to this issue.

Sorry about this!

**Comment by rajaseg** [comment]
> Hi Rajasekhar, The connectors service no longer uses a web server. It connects directly to the Elasticsearch server and polls. I will fix the Dockerfile and link the changes to this issue.
> 
> Sorry about this!

@tarekziade, Thank you very much. Please update the documentation in case of any change.
